### ISSUE TITLE
label file parsing problem

### ISSUE THREAD

**Issue by NimaAgm** [laclouis5/ObjectDetectionEval#1]
my label file are being generated from this tool(https://github.com/ivangrov/ModifiedOpenLabelling)
in labels txt in the first line there is two spaces which makes your code not work example labels
2 0.278125 0.878906 0.55 0.242188 
2 0.278125 0.878906 0.55 0.242188

**Comment by laclouis5** [comment]
I solved the issue in the latest commit of the development branch, this should work now. 

If you want to try it update your local copy of the repo and checkout the dev branch.

**Comment by NimaAgm** [comment]
Thanks your code is fine my dataset was the problem
